SET "TOOLCHAINDIR=D:\mingw32\bin"
SET "BINDIR=../../bin/x86"
SET "CXX=i686-w64-mingw32-g++"
SET "LIBDIR=../../lib/x86"
SET "MAKEEXE=%TOOLCHAINDIR%\mingw32-make.exe"
SET "OBJDIR=../../obj/x86"
SET "WRES=%TOOLCHAINDIR%\windres.exe -Iinclude/"

%MAKEEXE% CXX=%CXX% WRES="%WRES%" BINDIR=%BINDIR% LIBDIR=%LIBDIR% OBJDIR=%OBJDIR%